version: '3.7'

volumes:
  mariadb01:
    driver: local
  lininfosec01:
    driver: local

services:

  mariadb_lininfosec:
    image:
      mariadb:10
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=lininfosecpw
      - MYSQL_USER=lininfosec
      - MYSQL_PASSWORD=lininfosecpw
      - MYSQL_DATABASE=lininfosec
    volumes: 
      - mariadb01:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  lininfosec:
    build:
      context: ../../
      dockerfile: cmd/lininfosec/Dockerfile
    depends_on:
      - mariadb_lininfosec
    environment:
      - LININFOSEC_MYSQL_DSN=lininfosec:lininfosecpw@tcp(mariadb_lininfosec)/lininfosec
      - LININFOSEC_NOTIFICATION_ENDPOINT=backend.smartsla.local
    volumes:
      - lininfosec01:/data
    ports:
      - "9999:9999"
